models:
## LLM 纯文本
  internlm2-7b-text: # OOM
    type: "text"
    binary_path: "demos/build/text_llm_demo"
    model_path: "models/Internlm2-7B_W8A8_RK3588.rkllm"
    max_new_tokens: 512
    max_context_len: 4096

  qwen1.5-7b-text: 
    type: "text"
    binary_path: "demos/build/text_llm_demo"
    model_path: "models/Qwen1.5-7B_W8A8_RK3588_npu3.rkllm"
    max_new_tokens: 512
    max_context_len: 4096

  qwen2-1.5b-text: 
    type: "text"
    binary_path: "demos/build/text_llm_demo"
    model_path: "models/Qwen2-1.5B_W8A8_RK3588.rkllm"
    max_new_tokens: 512
    max_context_len: 4096

  qwen2-7b-text: 
    type: "text"
    binary_path: "demos/build/text_llm_demo"
    model_path: "models/Qwen2-7B_W8A8_RK3588.rkllm"
    max_new_tokens: 512
    max_context_len: 4096

  qwen2.5-7b-text:
    type: "text"
    binary_path: "demos/build/text_llm_demo"
    model_path: "models/Qwen2.5-7B_W8A8_RK3588.rkllm"
    max_new_tokens: 512
    max_context_len: 4096

  qwen3-0.6b-text:
    type: "text"
    binary_path: "demos/build/text_llm_demo"
    model_path: "models/Qwen3-0.6B_W8A8_RK3588.rkllm"
    max_new_tokens: 512
    max_context_len: 4096
  
  qwen3-1.7b-text:
    type: "text"
    binary_path: "demos/build/text_llm_demo"
    model_path: "models/Qwen3-1.7B-w8a8_rk3588.rkllm"
    max_new_tokens: 512
    max_context_len: 4096

  qwen3-4b-text:
    type: "text"
    binary_path: "demos/build/text_llm_demo"
    model_path: "models/Qwen3-4B-w8a8_rk3588.rkllm"
    max_new_tokens: 512
    max_context_len: 4096

  qwen3-8b-text: # OOM
    type: "text"
    binary_path: "demos/build/text_llm_demo"
    model_path: "models/Qwen3-8B_W8A8_RK3588_npu3.rkllm"
    max_new_tokens: 512
    max_context_len: 4096


  llama2-7b-text: # OOM 
    type: "text"
    binary_path: "demos/build/text_llm_demo"
    model_path: "models/Llama-2-7b-chat-hf_W8A8_RK3588_npu3.rkllm"
    max_new_tokens: 512
    max_context_len: 4096

  llama2-13b-text: # OOM
    type: "text"
    binary_path: "demos/build/text_llm_demo"
    model_path: "models/llama2-chat-13b-hf.rkllm"
    max_new_tokens: 512
    max_context_len: 4096

  llama3-8b-text: # OOM
    type: "text"
    binary_path: "demos/build/text_llm_demo"
    model_path: "models/Llama-3-8B_W8A8_RK3588.rkllm"
    max_new_tokens: 512
    max_context_len: 4096


## VLM 多模态
  internvl3.5-1b-npu:
    type: "vlm"
    binary_path: "demos/build/InternVL3.5-1B-NPU_VLM_NPU"
    vision_model_path: "models/internvl3.5-1b_vision_rk3588.rknn"
    llm_model_path: "models/Intern3.5-VL-1B-w8a8_rk3588.rkllm"
    max_new_tokens: 4096
    max_context_len: 4096

  internvl3.5-2b-npu:
    type: "vlm"
    binary_path: "demos/build/InternVL3.5-2B-NPU_VLM_NPU"
    vision_model_path: "models/internvl3.5-2b_vision_rk3588.rknn"
    llm_model_path: "models/Intern3.5-VL-2B-w8a8_rk3588.rkllm"
    max_new_tokens: 4096
    max_context_len: 4096

  internvl3.5-4b-npu:
    type: "vlm"
    binary_path: "demos/build/InternVL3.5-4B-NPU_VLM_NPU"
    vision_model_path: "models/internvl3.5-4b_vision_rk3588.rknn"
    llm_model_path: "models/Intern3.5-VL-4B-w8a8_rk3588.rkllm"
    max_new_tokens: 4096
    max_context_len: 4096

  qwen2.5-vl-7b-npu:
    type: "vlm"
    binary_path: "demos/build/Qwen2.5-VL-3B-NPU_VLM_NPU"
    vision_model_path: "models/qwen2_5-vl-7b_vision_rk3588.rknn"
    llm_model_path: "models/qwen2_5-vl-7b_instruct.rkllm"
    max_new_tokens: 4096
    max_context_len: 4096

  qwen3-vl-2b-npu:
    type: "vlm"
    binary_path: "demos/build/Qwen3-VL-2B-NPU_VLM_NPU"
    vision_model_path: "models/qwen3-vl_vision_rk3588.rknn"
    llm_model_path: "models/qwen3-vl-2B-w8a8-rk3588.rkllm"
    max_new_tokens: 4096
    max_context_len: 4096

  qwen3-vl-4b-npu:
    type: "vlm"
    binary_path: "demos/build/Qwen3-VL-4B-NPU_VLM_NPU"
    vision_model_path: "models/qwen3-vl_vision_rk3588.rknn"
    llm_model_path: "models/Qwen3-VL-4B.rkllm"
    max_new_tokens: 4096
    max_context_len: 4096

  qwen3-vl-8b-npu:
    type: "vlm"
    binary_path: "demos/build/Qwen3-VL-4B-NPU_VLM_NPU"
    vision_model_path: "models/qwen3-vl-8b_vision_rk3588.rknn"
    llm_model_path: "models/qwen3-vl-8b_instruct.rkllm"
    max_new_tokens: 4096
    max_context_len: 4096