models:
  qwen3-4b-text:
    type: "text"
    binary_path: "demos/build/text_llm_demo"
    model_path: "models/Qwen3-4B-rk3588-w8a8-opt-0-hybrid-ratio-0.0.rkllm"
    max_new_tokens: 512
    max_context_len: 4096

  qwen3-0.6b-text:
    type: "text"
    binary_path: "demos/build/text_llm_demo"
    model_path: "models/Qwen3-0.6B-rk3588-w8a8-opt-1-hybrid-ratio-0.0.rkllm"
    max_new_tokens: 512
    max_context_len: 4096

  internvl3.5-1b-npu:
    type: "vlm"
    binary_path: "third_party/InternVL3.5-1B-NPU/VLM_NPU"
    vision_model_path: "models/internvl3_5-1b_vision_rk3588.rknn"
    llm_model_path: "models/internvl3_5-1b-instruct_w8a8_rk3588.rkllm"
    max_new_tokens: 2048
    max_context_len: 4096

  internvl3.5-2b-npu:
    type: "vlm"
    binary_path: "third_party/InternVL3.5-2B-NPU/VLM_NPU"
    vision_model_path: "models/internvl3_5-2b_vision_rk3588.rknn"
    llm_model_path: "models/internvl3_5-2b-instruct_w8a8_rk3588.rkllm"
    max_new_tokens: 2048
    max_context_len: 4096

  internvl3.5-4b-npu:
    type: "vlm"
    binary_path: "third_party/InternVL3.5-4B-NPU/VLM_NPU"
    vision_model_path: "models/internvl3_5-4b_vision_rk3588.rknn"
    llm_model_path: "models/internvl3_5-4b-instruct_w8a8_rk3588.rkllm"
    max_new_tokens: 2048
    max_context_len: 4096

  qwen3-vl-2b-npu:
    type: "vlm"
    binary_path: "third_party/Qwen3-VL-2B-NPU/VLM_NPU"
    vision_model_path: "models/qwen3-vl-2b_vision_672_rk3588.rknn"
    llm_model_path: "models/qwen3-vl-2b-instruct_w8a8_rk3588.rkllm"
    max_new_tokens: 2048
    max_context_len: 4096

  qwen3-vl-4b-npu:
    type: "vlm"
    binary_path: "third_party/Qwen3-VL-4B-NPU/VLM_NPU"
    vision_model_path: "models/qwen3-vl-4b-instruct_vision_448_rk3588.rknn"
    llm_model_path: "models/qwen3-vl-4b-instruct_w8a8_rk3588.rkllm"
    max_new_tokens: 2048
    max_context_len: 4096